USE POINTS;
CREATE TABLE IF NOT EXISTS POINTS.EMPLOYEE (
    EMPLOYEE_ID INT NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT UC_EMAIL UNIQUE (EMAIL)
); 
