USE POINTS;
CREATE TABLE IF NOT EXISTS POINTS.POINT_TALLY (
    ID INT NOT NULL AUTO_INCREMENT,
    EMPLOYEE_ID INT NOT NULL,
    ACTIVITY_ID INT NOT NULL,
    ENT_DT TIMESTAMP NOT NULL,
    LOAD_FILE VARCHAR(255),-- For audit purposes
    PRIMARY KEY (ID), 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);
