USE POINTS;
CREATE TABLE IF NOT EXISTS POINTS.REF_POINTS (
    EMPLOYEE_ID INT NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    Q1_PTS INT,
    Q2_PTS INT,
    Q3_PTS INT,
    Q4_PTS INT,
    FY_PTS INT AS (Q1_PTS+Q2_PTS+Q3_PTS+Q4_PTS),
    MOD_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (EMPLOYEE_ID), 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);