USE POINTS;
INSERT INTO POINTS.ACTIVITY (ACTIVITY_NAME, POINT_VALUE) VALUES ('TOWN HALL',40) ON DUPLICATE KEY UPDATE POINT_VALUE=40;
INSERT INTO POINTS.ACTIVITY (ACTIVITY_NAME, POINT_VALUE) VALUES ('ANNUAL TOUR', 50) ON DUPLICATE KEY UPDATE POINT_VALUE=50;
INSERT INTO POINTS.ACTIVITY (ACTIVITY_NAME, POINT_VALUE) VALUES ('PULSE SURVEYS',5) ON DUPLICATE KEY UPDATE POINT_VALUE=5;
INSERT INTO POINTS.ACTIVITY (ACTIVITY_NAME, POINT_VALUE) VALUES ('BRAVO - RECEIVED', 30) ON DUPLICATE KEY UPDATE POINT_VALUE=30;
INSERT INTO POINTS.ACTIVITY (ACTIVITY_NAME, POINT_VALUE) VALUES ('BRAVO - SENT',10) ON DUPLICATE KEY UPDATE POINT_VALUE=10;
INSERT INTO POINTS.ACTIVITY (ACTIVITY_NAME, POINT_VALUE) VALUES ('APPLAUD - RECEIVED', 10) ON DUPLICATE KEY UPDATE POINT_VALUE=10;
INSERT INTO POINTS.ACTIVITY (ACTIVITY_NAME, POINT_VALUE) VALUES ('APPLAUD - SENT', 2) ON DUPLICATE KEY UPDATE POINT_VALUE=2;
