USE POINTS;
INSERT INTO POINTS.EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (100000, 'Bat', 'Man') ON DUPLICATE KEY UPDATE FIRST_NAME = 'Bat', LAST_NAME = 'Man';
INSERT INTO POINTS.EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (100001, 'Peter', 'Griffin') ON DUPLICATE KEY UPDATE FIRST_NAME = 'Peter', LAST_NAME = 'Griffin';
INSERT INTO POINTS.EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (100002, 'Ro', 'Bin') ON DUPLICATE KEY UPDATE FIRST_NAME = 'Ro', LAST_NAME = 'Bin';
INSERT INTO POINTS.EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (100003, 'Johnny', 'Bravo') ON DUPLICATE KEY UPDATE FIRST_NAME = 'Johnny', LAST_NAME = 'Bravo';
INSERT INTO POINTS.EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (100004, 'The', 'Greatest') ON DUPLICATE KEY UPDATE FIRST_NAME = 'The', LAST_NAME = 'Greatest';
INSERT INTO POINTS.EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (100005, 'Ed', 'Sheeran') ON DUPLICATE KEY UPDATE FIRST_NAME = 'Ed', LAST_NAME = 'Sheeran';
INSERT INTO POINTS.EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (100006, 'J', 'Biebs') ON DUPLICATE KEY UPDATE FIRST_NAME = 'J', LAST_NAME = 'Biebs';