USE POINTS;
INSERT INTO POINTS.EMPLOYEE (FIRST_NAME, LAST_NAME, EMPLOYEE_ID) VALUES ('Bat', 'Man', 100000) ON DUPLICATE KEY UPDATE FIRST_NAME = 'Bat', LAST_NAME = 'Man';
INSERT INTO POINTS.EMPLOYEE (FIRST_NAME, LAST_NAME, EMPLOYEE_ID) VALUES ('Peter', 'Griffin', 100001) ON DUPLICATE KEY UPDATE FIRST_NAME = 'Peter', LAST_NAME = 'Griffin';
INSERT INTO POINTS.EMPLOYEE (FIRST_NAME, LAST_NAME, EMPLOYEE_ID) VALUES ('Ro', 'Bin', 100002) ON DUPLICATE KEY UPDATE FIRST_NAME = 'Ro', LAST_NAME = 'Bin';
INSERT INTO POINTS.EMPLOYEE (FIRST_NAME, LAST_NAME, EMPLOYEE_ID) VALUES ('Johnny', 'Bravo', 100003) ON DUPLICATE KEY UPDATE FIRST_NAME = 'Johnny', LAST_NAME = 'Bravo';
INSERT INTO POINTS.EMPLOYEE (FIRST_NAME, LAST_NAME, EMPLOYEE_ID) VALUES ('The', 'Greatest', 100004) ON DUPLICATE KEY UPDATE FIRST_NAME = 'The', LAST_NAME = 'Greatest';
INSERT INTO POINTS.EMPLOYEE (FIRST_NAME, LAST_NAME, EMPLOYEE_ID) VALUES ('Ed', 'Sheeran', 100004) ON DUPLICATE KEY UPDATE FIRST_NAME = 'Ed', LAST_NAME = 'Sheeran';
INSERT INTO POINTS.EMPLOYEE (FIRST_NAME, LAST_NAME, EMPLOYEE_ID) VALUES ('J', 'Biebs', 100005) ON DUPLICATE KEY UPDATE FIRST_NAME = 'J', LAST_NAME = 'Biebs';