USE POINTS;
INSERT INTO POINTS.POINT_TALLY (EMPLOYEE_ID, ACTIVITY_ID, LOAD_FILE) VALUES (100000, 1, 'MOCK_DATA.XLS') ON DUPLICATE KEY UPDATE EMPLOYEE_ID = 100000, ACTIVITY_ID = 1, LOAD_FILE = 'MOCK_DATA.XLS';
INSERT INTO POINTS.POINT_TALLY (EMPLOYEE_ID, ACTIVITY_ID, LOAD_FILE) VALUES (100000, 2, 'MOCK_DATA.XLS') ON DUPLICATE KEY UPDATE EMPLOYEE_ID = 100000, ACTIVITY_ID = 2, LOAD_FILE = 'MOCK_DATA.XLS';
INSERT INTO POINTS.POINT_TALLY (EMPLOYEE_ID, ACTIVITY_ID, LOAD_FILE) VALUES (100000, 3, 'MOCK_DATA.XLS') ON DUPLICATE KEY UPDATE EMPLOYEE_ID = 100000, ACTIVITY_ID = 3, LOAD_FILE = 'MOCK_DATA.XLS';
INSERT INTO POINTS.POINT_TALLY (EMPLOYEE_ID, ACTIVITY_ID, LOAD_FILE) VALUES (100001, 1, 'MOCK_DATA.XLS') ON DUPLICATE KEY UPDATE EMPLOYEE_ID = 100001, ACTIVITY_ID = 1, LOAD_FILE = 'MOCK_DATA.XLS';
