USE POINTS;
CREATE TABLE POINTS.ACTIVITY (
    ID int NOT NULL AUTO_INCREMENT,
    ACTIVITY_NAME varchar(255) NOT NULL,
    POINT_VALUE int,
    PRIMARY KEY (ID),
    CONSTRAINT UC_Activity UNIQUE (ACTIVITY_NAME)
); 
