USE POINTS;
CREATE TABLE IF NOT EXISTS POINTS.ACTIVITY (
    ID INT NOT NULL AUTO_INCREMENT,
    ACTIVITY_NAME VARCHAR(255) NOT NULL,
    POINT_VALUE INT,
    PRIMARY KEY (ID),
    CONSTRAINT UC_Activity UNIQUE (ACTIVITY_NAME)
); 
