USE POINTS;
CREATE TABLE POINTS.EMPLOYEE (
    ID int NOT NULL AUTO_INCREMENT,
    FIRST_NAME varchar(255) NOT NULL,
    LAST_NAME varchar(255) NOT NULL,
    EMPLOYEE_ID int NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UC_EMPLOYEE_ID UNIQUE (EMPLOYEE_ID)
); 
