USE POINTS;
INSERT INTO POINTS.ACTIVITY (ID, ACTIVITY_NAME, POINT_VALUE) VALUES (100, 'TOWN HALL',40) ON DUPLICATE KEY UPDATE ACTIVITY_NAME = 'TOWN HALL', POINT_VALUE=40;
INSERT INTO POINTS.ACTIVITY (ID, ACTIVITY_NAME, POINT_VALUE) VALUES (200, 'ANNUAL TOUR', 50) ON DUPLICATE KEY UPDATE ACTIVITY_NAME = 'ANNUAL TOUR', POINT_VALUE=50;
INSERT INTO POINTS.ACTIVITY (ID, ACTIVITY_NAME, POINT_VALUE) VALUES (300, 'PULSE SURVEYS',5) ON DUPLICATE KEY UPDATE ACTIVITY_NAME = 'PULSE SURVEYS', POINT_VALUE=5;
INSERT INTO POINTS.ACTIVITY (ID, ACTIVITY_NAME, POINT_VALUE) VALUES (400, 'BRAVO - RECEIVED', 30) ON DUPLICATE KEY UPDATE ACTIVITY_NAME = 'BRAVO - RECEIVED', POINT_VALUE=30;
INSERT INTO POINTS.ACTIVITY (ID, ACTIVITY_NAME, POINT_VALUE) VALUES (500, 'BRAVO - SENT',10) ON DUPLICATE KEY UPDATE ACTIVITY_NAME = 'BRAVO - SENT', POINT_VALUE=10;
INSERT INTO POINTS.ACTIVITY (ID, ACTIVITY_NAME, POINT_VALUE) VALUES (600, 'APPLAUD - RECEIVED', 10) ON DUPLICATE KEY UPDATE ACTIVITY_NAME = 'APPLAUD - RECEIVED', POINT_VALUE=10;
INSERT INTO POINTS.ACTIVITY (ID, ACTIVITY_NAME, POINT_VALUE) VALUES (700, 'APPLAUD - SENT', 2) ON DUPLICATE KEY UPDATE ACTIVITY_NAME = 'APPLAUD - SENT', POINT_VALUE=2;
