USE POINTS;
INSERT INTO POINTS.EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (100000, 'Bat', 'Man', 'fake@fake.com') ON DUPLICATE KEY UPDATE FIRST_NAME = 'Bat', LAST_NAME = 'Man';
INSERT INTO POINTS.EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (100001, 'Peter', 'Griffin', 'fake1@fake.com') ON DUPLICATE KEY UPDATE FIRST_NAME = 'Peter', LAST_NAME = 'Griffin';
INSERT INTO POINTS.EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (100002, 'Ro', 'Bin', 'fake2@fake.com') ON DUPLICATE KEY UPDATE FIRST_NAME = 'Ro', LAST_NAME = 'Bin';
INSERT INTO POINTS.EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (100003, 'Johnny', 'Bravo', 'fake3@fake.com') ON DUPLICATE KEY UPDATE FIRST_NAME = 'Johnny', LAST_NAME = 'Bravo';
INSERT INTO POINTS.EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (100004, 'The', 'Greatest', 'fake4@fake.com') ON DUPLICATE KEY UPDATE FIRST_NAME = 'The', LAST_NAME = 'Greatest';
INSERT INTO POINTS.EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (100005, 'Ed', 'Sheeran', 'fake5@fake.com') ON DUPLICATE KEY UPDATE FIRST_NAME = 'Ed', LAST_NAME = 'Sheeran';
INSERT INTO POINTS.EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (100006, 'J', 'Biebs', 'fake6@fake.com') ON DUPLICATE KEY UPDATE FIRST_NAME = 'J', LAST_NAME = 'Biebs';
