USE POINTS;
INSERT INTO POINTS.EVENT (EVENT_NAME, ENT_DT) VALUES ('PULSE Product Session', (SELECT TIMESTAMP('2017-05-30')));
INSERT INTO POINTS.EVENT (EVENT_NAME, ENT_DT) VALUES ('Hackathon', (SELECT TIMESTAMP('2017-05-10')));
INSERT INTO POINTS.EVENT (EVENT_NAME, ENT_DT) VALUES ('Annual Tour', (SELECT TIMESTAMP('2017-05-11')));
INSERT INTO POINTS.EVENT (EVENT_NAME, ENT_DT) VALUES ('PULSE Product Session', (SELECT TIMESTAMP('2017-04-30')));
INSERT INTO POINTS.EVENT (EVENT_NAME, ENT_DT) VALUES ('Town Hall GTA-BKS', (SELECT TIMESTAMP('2017-05-20')));
INSERT INTO POINTS.EVENT (EVENT_NAME, ENT_DT) VALUES ('Town Hall GTA-GWCM', (SELECT TIMESTAMP('2017-05-11')));